### ISSUE TITLE
use with worker_threads

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [wclr/ts-node-dev#293]
Hi, 

I found some workaround to use worker threads in ts-node, but in conjunction with ts-node-dev it will throw errors like: 

`error TS2695: Left side of comma operator is unused and has no side effects.\r\n'`

Now the code I use is this:.

```
const stream = new Worker(`
    require('ts-node/register'); // <<< i guess here must be the problem
    require(require('worker_threads').workerData.path);`, {
    eval: true,
    workerData: { path:'./worker.ts' }
})           

```

Should I be using something like ts-node-register to fix? 

Update:

used 

```
require('ts-node-dev')
```
and it worked. not sure if its bad practice.

**Comment by yuriyyakym** [comment]
This is how I've accomplished this:
```ts
  new Worker(require.resolve(`./worker`), {
    execArgv:
      process.env.NODE_ENV === 'development'
        ? ['-r', 'ts-node/register/transpile-only']
        : undefined,
  });
```

To run production I use typescript dist output, so that `worker` is available there and no need for additional args.

For dev environment I am requiring `ts-node/register/transpile-only`, so that nodejs knows how to import .ts file.
`transpile-only` is used for faster build. You can use default `ts-node/register`.

If you run production using `ts-node`, then you should set `execArgv: ['-r', 'ts-node/register/transpile-only']`

**Comment by jhjeongilts** [comment]
@yuriyyakym Thank you. 👍

**Comment by joschan21** [comment]
@yuriyyakym thanks so much, saved me a ton of headache
